baseURL = '/'
languageCode = 'en-us'
title = 'BFNet Docs'

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    # replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false